# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message-format.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message-format.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14message-format.proto\"\x95\x01\n\x08NodeData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\treport_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\"\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x14.NodeData.SensorData\x1a\x33\n\nSensorData\x12\x11\n\tdata_type\x18\x01 \x01(\x05\x12\x12\n\ndata_value\x18\x02 \x01(\x02\x62\x06proto3'
)




_NODEDATA_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='NodeData.SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_type', full_name='NodeData.SensorData.data_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_value', full_name='NodeData.SensorData.data_value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=174,
)

_NODEDATA = _descriptor.Descriptor(
  name='NodeData',
  full_name='NodeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NodeData.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='report_id', full_name='NodeData.report_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='NodeData.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='NodeData.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NODEDATA_SENSORDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=174,
)

_NODEDATA_SENSORDATA.containing_type = _NODEDATA
_NODEDATA.fields_by_name['data'].message_type = _NODEDATA_SENSORDATA
DESCRIPTOR.message_types_by_name['NodeData'] = _NODEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeData = _reflection.GeneratedProtocolMessageType('NodeData', (_message.Message,), {

  'SensorData' : _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
    'DESCRIPTOR' : _NODEDATA_SENSORDATA,
    '__module__' : 'message_format_pb2'
    # @@protoc_insertion_point(class_scope:NodeData.SensorData)
    })
  ,
  'DESCRIPTOR' : _NODEDATA,
  '__module__' : 'message_format_pb2'
  # @@protoc_insertion_point(class_scope:NodeData)
  })
_sym_db.RegisterMessage(NodeData)
_sym_db.RegisterMessage(NodeData.SensorData)


# @@protoc_insertion_point(module_scope)
